backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: "fr"

collections:
  - name: "actus"
    label: "Actualités"
    file: "content/actus.json"
    fields:
      - { label: "Liste des actualités", name: "actus", widget: "list", fields: [
          { label: "Titre", name: "title", widget: "string" },
          { label: "Date", name: "date", widget: "datetime" },
          { label: "Texte", name: "text", widget: "text" },
          { label: "Image", name: "image", widget: "image", required: false }
        ]}


  - name: "tarifs"
    label: "Tarifs Licences"
    files:
      - label: "Tarifs actuels"
        name: "tarifs"
        file: "content/tarifs.json"
        fields:
          - { label: "Année", name: "annee", widget: "string" }
          - label: "Licences"
            name: "licences"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Tarif", name: "tarif", widget: "string" }

  - name: "rando"
    label: "Rando annuelle"
    files:
      - label: "Rando principale"
        name: "rando"
        file: "content/rando.json"
        fields:
          - { label: "Nom", name: "nom", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Flyer", name: "flyer", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "text" }
