backend:
  name: git-gateway
  branch: main
  
locale: 'fr'

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "actus"
    label: "Actualit√©s"
    files:
      - file: "content/actus.json"
        label: "Liste des actualit√©s"
        name: "actus"
        fields:
          - label: "Actualit√©s"
            name: "actus"
            widget: "list"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Texte", name: "text", widget: "text" }

              # üëá On remplace ici l'ancien champ unique par une liste d'images
              - label: "Images"
                name: "images"
                widget: "list"
                field:
                  label: "Image"
                  name: "image"
                  widget: "image"
                  required: false


  - name: "tarifs"
    label: "Tarifs Licences"
    files:
      - label: "Tarifs actuels"
        name: "tarifs"
        file: "content/tarifs.json"
        fields:
          - { label: "Ann√©e", name: "annee", widget: "string" }
          - label: "Licences"
            name: "licences"
            widget: "list"
            fields:
              - { label: "Type", name: "type", widget: "string" }
              - { label: "Tarif", name: "tarif", widget: "string" }

  - name: "evenements"
    label: "√âv√©nements"
    files:
      - file: "content/evenements.json"
        label: "Liste des √©v√©nements"
        name: "evenements"
        fields:
          - label: "√âv√©nements"
            name: "evenements"
            widget: "list"
            fields:
              - { label: "Ann√©e", name: "annee", widget: "number" }
              - { label: "Titre", name: "titre", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "Lien d'inscription (HelloAsso...)", name: "lien", widget: "string", required: false }

